In [ ]:
import pandas as pd
df_golden_set= pd.read_csv('GoldenSetNSR(Sheet1).csv')
df_golden_set

,Question,Query
0,What was the sales volume today?,"EVALUATE ROW( ""Unit Cases"", CALCULATE( [Unit C..."
1,What was the sales volume yesterday?,"EVALUATE ROW( ""Unit Cases"", CALCULATE( [Unit C..."
2,What was the sales volume this week?,"EVALUATE ROW( ""Unit Cases WTD"", CALCULATE( [Un..."
3,What was the sales volume last week?,"EVALUATE ROW( ""Unit Cases WTD"", CALCULATE( [Un..."
4,What was the sales volume month to date (MTD)?,"EVALUATE\nROW(\n ""Unit Cases MTD"",\n ..."
5,What was the sales volume last month?,"EVALUATE\nROW(\n ""Unit Cases"",\n CAL..."
6,What was the sales volume year to date (YTD)?,"EVALUATE\nROW(\n ""Unit Cases YTD"",\n ..."
7,What was the sales volume last year?,"EVALUATE\nROW(\n ""Unit Cases Last Year"",\n ..."
8,Top 10 brands by sales volume year to date (YTD).,"EVALUATE\nTOPN(\n 10,\n SUMMARIZECOLUMNS..."
9,Top 10 brands with the most sales year to date...,"EVALUATE\nTOPN(\n 10,\n SUMMARIZECOLUMNS..."
10,Top 10 brands with the least sales year to dat...,"EVALUATE\nTOPN(\n 10,\n SUMMARIZECOLUMNS..."
11,How does the sales volume of the Quatro brand ...,"EVALUATE\nROW(\n ""Brand Group"", ""Quatro"",\n..."
12,What was the total sales YoY% in the last mont...,"EVALUATE\nROW(\n ""Net Sales Revenue YoY %"",..."
13,Top 5 categories by net sales in the last year.,"EVALUATE\nTOPN(\n 5,\n SUMMARIZECOLUMNS(..."
14,How does the sales volume of the Quatro brand ...,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...
15,Top 10 subcategories by volume in each quarter...,EVALUATE\nGENERATE(\n VALUES('Period'[Quart...
16,What was the total sales volume yesterday?,"EVALUATE\nROW(\n ""Unit Cases"",\n CAL..."
17,Which channel has the highest sales week to da...,"EVALUATE\nTOPN(\n 1,\n SUMMARIZECOLUMNS(..."
18,How does the sales volume of the Quatro brand ...,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...
19,What is the share (% units) of the Flavors cat...,"EVALUATE\nROW(\n ""% Unit Cases Share"",\n ..."
20,Which are the Top 3 brands with the best perfo...,"EVALUATE\nTOPN(\n 3,\n SUMMARIZECOLUMNS(..."
21,Top 3 categories by volume quarter to date (QTD).,"EVALUATE\nTOPN(\n 3,\n SUMMARIZECOLUMNS(..."
22,Top 5 brands by revenue in the previous year.,"EVALUATE\nTOPN(\n 5,\n SUMMARIZECOLUMNS(..."
23,Top 3 brands by volume within each category in...,EVALUATE\nGENERATE(\n VALUES('Product'[LT1....
24,Volume by package type in the past week.,EVALUATE\nSUMMARIZECOLUMNS(\n 'Package'[Pac...
25,What was the YoY% in september of the volume o...,"EVALUATE\nROW(\n ""Unit Cases YoY %"",\n ..."
26,What is the revenue by channel in the last month?,EVALUATE\nSUMMARIZECOLUMNS(\n 'Channel'[LT1...
27,What is the Top 5 of leading brands by channel...,EVALUATE\nGENERATE(\n VALUES('Channel'[LT1....
28,How did the YoY volume of the Brisa brand vary...,"EVALUATE\nROW(\n ""Unit Cases YoY %"",\n ..."
29,What is the unit mix in Cali within the Flavor...,"EVALUATE\nROW(\n ""Unit Mix %"",\n DIV..."
30,Sales comparison for this week versus previous...,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Week...
31,What was the highest sales volume ever for thi...,"EVALUATE\nTOPN(\n 1,\n SUMMARIZECOLUMNS(..."
32,What is the revenue by channel in the last mon...,EVALUATE\nSUMMARIZECOLUMNS(\n 'Channel'[LT1...
33,Which customer is underdeveloped versus my nat...,EVALUATE\nFILTER(\n ADDCOLUMNS(\n SU...
34,What was the year-over-year change in total NS...,"EVALUATE\nROW(\n ""Net Sales Revenue % vs PY..."
35,Which channel showed the highest YoY growth in...,"EVALUATE\nTOPN(\n 1,\n SUMMARIZECOLUMNS(..."
36,What was the YoY growth of NSR in Cali two mon...,"EVALUATE\nROW(\n ""Net Sales Revenue YoY %"",..."
37,Which subcategories experienced a year-over-ye...,EVALUATE\nFILTER(\n SUMMARIZECOLUMNS(\n ...
38,Top 5 brands with the highest YoY growth in NS...,"EVALUATE\nTOPN(\n 5,\n SUMMARIZECOLUMNS(..."
39,How�s Coke performing lately?,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...
40,What�s happening with Quatro this year?,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...
41,Anything new with Del Valle recently?,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...
42,How strong is COKE REDUCED SUGAR this quarter?,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...
43,Is the Cola portfolio holding up?,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...
44,Are we seeing any lift for FUZE TEA-KO lately?,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...
45,How�s the flavors category trending?,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...
46,What�s up with the Stills category?,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...
47,Is the Juice category back on track?,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...
48,Which category is leading volume this quarter?,"EVALUATE\nTOPN(\n 1,\n SUMMARIZECOLUMNS(..."
49,Which segment is underperforming the most?,"EVALUATE\nTOPN(\n 1,\n SUMMARIZECOLUMNS(..."
50,How�s Modern Trade behaving lately?,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...
51,Is Traditional Trade facing any slowdown?,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...
52,Who�s leading growth across channels?,"EVALUATE\nTOPN(\n 5,\n SUMMARIZECOLUMNS(..."
53,Is Modern Trade outperforming Traditional Trade?,EVALUATE\nSUMMARIZECOLUMNS(\n 'Channel'[LT1...
54,Which regions are trending up?,EVALUATE\nFILTER(\n SUMMARIZECOLUMNS(\n ...
55,Where are we growing the fastest?,"EVALUATE\nTOPN(\n 10,\n SUMMARIZECOLUMNS..."
56,Which city sold the most UCs last quarter?,"EVALUATE\nTOPN(\n 1,\n SUMMARIZECOLUMNS(..."
57,What was the total UC per trademark in the las...,EVALUATE\nSUMMARIZECOLUMNS(\n 'Product'[LT1...
58,Which category has sold the most UC this year?,"EVALUATE\nTOPN(\n 1,\n SUMMARIZECOLUMNS(..."

In [ ]:
import requests
import json
from tqdm import tqdm

url = "https://emt-ai-pbi-agent.azurewebsites.net/et/api/pbi-data-xmla-service"

headers = {
    "client_Id": "",
    "client_secret": "",
    "tenant_Id": "",
    "workspace": "NSR LATAM",
    "catalog": "NSR LATAM Cube",
    "aut_url": "https://login.microsoftonline.com/",
    "scope": "https://analysis.windows.net/powerbi/api/.default",
    "user_id": "rcasianomorales@coca-cola.com",
    "Content-Type": "application/json",
    "Authorization": "",
}

200
[{'[Unit Cases]': 2166416.1318}]

In [23]:
#Create a dataframe to store the results, including response time and status code
results_df = []
for i in tqdm(range(len(df_golden_set))):
	query = df_golden_set['Query'][i]
	payload = {
		"query": query,
		"msg": {}
	}
	response = requests.post(url, headers=headers, json=payload)
	results_df.append({
		"Query": query,
		"Status Code": response.status_code,
		"Response Time": response.elapsed.total_seconds(),
		"Response": response.json()
	})
results_df= pd.DataFrame(results_df)
results_df

100%|██████████| 59/59 [02:58<00:00,  3.02s/it]

,Query,Status Code,Response Time,Response
0,"EVALUATE ROW( ""Unit Cases"", CALCULATE( [Unit C...",200,2.819151,[{'[Unit Cases]': 2166416.1318}]
1,"EVALUATE ROW( ""Unit Cases"", CALCULATE( [Unit C...",200,2.030813,[{'[Unit Cases]': 2136281.9846}]
2,"EVALUATE ROW( ""Unit Cases WTD"", CALCULATE( [Un...",200,1.948131,[{'[Unit Cases WTD]': 2166416.1318}]
3,"EVALUATE ROW( ""Unit Cases WTD"", CALCULATE( [Un...",200,1.985195,[{'[Unit Cases WTD]': 2166416.1318}]
4,"EVALUATE\nROW(\n ""Unit Cases MTD"",\n ...",200,2.890041,[{'[Unit Cases MTD]': 2166416.1318}]
5,"EVALUATE\nROW(\n ""Unit Cases"",\n CAL...",200,2.318981,[{'[Unit Cases]': 89945426.3419}]
6,"EVALUATE\nROW(\n ""Unit Cases YTD"",\n ...",200,3.096739,[{'[Unit Cases YTD]': 2166416.1318}]
7,"EVALUATE\nROW(\n ""Unit Cases Last Year"",\n ...",200,2.067876,[{'[Unit Cases Last Year]': 697398148.2863}]
8,"EVALUATE\nTOPN(\n 10,\n SUMMARIZECOLUMNS...",200,2.411331,[{'Product[LT1.2 - Brand Group]': 'Coca-Cola L...
9,"EVALUATE\nTOPN(\n 10,\n SUMMARIZECOLUMNS...",200,2.215374,"{'error': 'General Error: Query (8, 17) The va..."
10,"EVALUATE\nTOPN(\n 10,\n SUMMARIZECOLUMNS...",200,2.378600,"{'error': 'General Error: Query (8, 17) The va..."
11,"EVALUATE\nROW(\n ""Brand Group"", ""Quatro"",\n...",200,2.776389,"[{'[Brand Group]': 'Quatro', '[Period]': '2025..."
12,"EVALUATE\nROW(\n ""Net Sales Revenue YoY %"",...",200,9.579280,[{'[Net Sales Revenue YoY %]': 0.1579304287185...
13,"EVALUATE\nTOPN(\n 5,\n SUMMARIZECOLUMNS(...",200,2.926956,"[{'Product[LT1.5 - Category]': 'Colas', '[Net ..."
14,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...,200,7.055807,"[{'Period[Month 445]': '2025 Dec', '[Unit Case..."
15,EVALUATE\nGENERATE(\n VALUES('Period'[Quart...,200,2.813535,"[{'Period[Quarter 445]': '2026 Q1', 'Product[L..."
16,"EVALUATE\nROW(\n ""Unit Cases"",\n CAL...",200,7.339387,[{'[Unit Cases]': 2136281.9846}]
17,"EVALUATE\nTOPN(\n 1,\n SUMMARIZECOLUMNS(...",200,2.114621,"{'error': 'General Error: Query (8, 17) The va..."
18,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...,200,7.205546,"[{'Period[Month 445]': '2025 Dec', '[Unit Case..."
19,"EVALUATE\nROW(\n ""% Unit Cases Share"",\n ...",200,2.127470,[{'[% Unit Cases Share]': 0.10306053223722131}]
20,"EVALUATE\nTOPN(\n 3,\n SUMMARIZECOLUMNS(...",200,8.230858,[]
21,"EVALUATE\nTOPN(\n 3,\n SUMMARIZECOLUMNS(...",200,2.336045,"[{'Product[LT1.5 - Category]': 'Colas', '[Unit..."
22,"EVALUATE\nTOPN(\n 5,\n SUMMARIZECOLUMNS(...",200,7.486792,[{'Product[LT1.2 - Brand Group]': 'Coca-Cola L...
23,EVALUATE\nGENERATE(\n VALUES('Product'[LT1....,200,2.466111,[{'Product[LT1.5 - Category]': 'Active Hydrati...
24,EVALUATE\nSUMMARIZECOLUMNS(\n 'Package'[Pac...,200,1.982755,"{'error': 'General Error: Query (3, 5) Column ..."
25,"EVALUATE\nROW(\n ""Unit Cases YoY %"",\n ...",200,2.659086,[{'[Unit Cases YoY %]': -0.003845569486297446}]
26,EVALUATE\nSUMMARIZECOLUMNS(\n 'Channel'[LT1...,200,2.857981,[{'Channel[LT1.3 - Channel Macro Group]': 'Tra...
27,EVALUATE\nGENERATE(\n VALUES('Channel'[LT1....,200,2.748924,[{'Channel[LT1.3 - Channel Macro Group]': 'D2C...
28,"EVALUATE\nROW(\n ""Unit Cases YoY %"",\n ...",200,2.446047,[{'[Unit Cases YoY %]': 0.06434515426207077}]
29,"EVALUATE\nROW(\n ""Unit Mix %"",\n DIV...",200,1.998088,"{'error': 'General Error: Query (7, 29) Column..."
30,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Week...,200,1.982476,"{'error': 'General Error: Query (18, 13) The v..."
31,"EVALUATE\nTOPN(\n 1,\n SUMMARIZECOLUMNS(...",200,2.313157,"[{'Period[Month 445]': '2025 Dec', '[Unit Case..."
32,EVALUATE\nSUMMARIZECOLUMNS(\n 'Channel'[LT1...,200,2.268048,"{'error': 'General Error: Query (12, 13) The v..."
33,EVALUATE\nFILTER(\n ADDCOLUMNS(\n SU...,200,2.742341,[{'Ship To[LT1.2 - Customer]': 'Globalia Corpo...
34,"EVALUATE\nROW(\n ""Net Sales Revenue % vs PY...",200,2.848846,[{'[Net Sales Revenue % vs PY]': 0.04157752265...
35,"EVALUATE\nTOPN(\n 1,\n SUMMARIZECOLUMNS(...",200,2.422575,[{'Channel[LT1.3 - Channel Macro Group]': 'Mod...
36,"EVALUATE\nROW(\n ""Net Sales Revenue YoY %"",...",200,2.027041,"{'error': 'General Error: Query (6, 25) Column..."
37,EVALUATE\nFILTER(\n SUMMARIZECOLUMNS(\n ...,200,2.482514,[{'Product[LT1.4 - Sub-Category]': 'Fruit Soy'...
38,"EVALUATE\nTOPN(\n 5,\n SUMMARIZECOLUMNS(...",200,2.450728,[{'Product[LT1.2 - Brand Group]': 'Del Valle K...
39,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...,200,3.002614,"[{'Period[Month 445]': '2025 Dec', '[Net Sales..."
40,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...,200,3.022853,"[{'Period[Month 445]': '2025 Dec', '[Net Sales..."
41,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...,200,2.973645,"[{'Period[Month 445]': '2025 Dec', '[Net Sales..."
42,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...,200,2.345578,[]
43,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...,200,3.134573,"[{'Period[Month 445]': '2025 Dec', '[Net Sales..."
44,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...,200,1.959945,[]
45,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...,200,3.058688,"[{'Period[Month 445]': '2025 Dec', '[Net Sales..."
46,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...,200,1.956211,[]
47,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...,200,1.993628,[]
48,"EVALUATE\nTOPN(\n 1,\n SUMMARIZECOLUMNS(...",200,2.285283,"[{'Product[LT1.5 - Category]': 'Colas', '[Unit..."
49,"EVALUATE\nTOPN(\n 1,\n SUMMARIZECOLUMNS(...",200,2.933517,"[{'Product[LT1.7 - Segment]': 'Unassigned', '[..."
50,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...,200,2.521390,[]
51,EVALUATE\nSUMMARIZECOLUMNS(\n 'Period'[Mont...,200,2.363368,[]
52,"EVALUATE\nTOPN(\n 5,\n SUMMARIZECOLUMNS(...",200,2.305262,[{'Channel[LT1.3 - Channel Macro Group]': 'Mod...
53,EVALUATE\nSUMMARIZECOLUMNS(\n 'Channel'[LT1...,200,2.414945,[]
54,EVALUATE\nFILTER(\n SUMMARIZECOLUMNS(\n ...,200,2.085192,"{'error': 'General Error: Query (4, 9) Column ..."
55,"EVALUATE\nTOPN(\n 10,\n SUMMARIZECOLUMNS...",200,2.336383,"{'error': 'General Error: Query (5, 9) Column ..."
56,"EVALUATE\nTOPN(\n 1,\n SUMMARIZECOLUMNS(...",200,2.626900,"[{'Ship From[BU Ship From]': 'Medellin', '[Uni..."
57,EVALUATE\nSUMMARIZECOLUMNS(\n 'Product'[LT1...,200,2.675803,[{'Product[LT1.3 - Trademark Category]': 'Coca...
58,"EVALUATE\nTOPN(\n 1,\n SUMMARIZECOLUMNS(...",200,2.709669,"[{'Product[LT1.5 - Category]': 'Colas', '[Unit..."

In [24]:
results_df.to_csv('golden_set_results.csv', index=False)